name: Golang Docker CD

on: [push, pull_request]

jobs:
  deploy-container-images-tags:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set PREREL environment variable
        env:
          TAG: ${{ github.ref }}
        run: echo "PREREL=$(if [[ $TAG =~ "alpha" ]] || [[ $TAG =~ "beta" ]] || [[ $TAG =~ "rc" ]]; then echo "true"; else echo "false"; fi;)" >> $GITHUB_ENV

      - name: Generate Docker Metadata
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        env:
          PREFIX: test-
        with:
          flavor: |
            latest=false
            prefix=${{ env.PREFIX }}
          images: |
            brenekh/docker-hub-ghcr-test
            ghcr.io/brenekh/docker-hub-ghcr-test
          tags: |
            type=ref,event=branch
            type=semver,pattern=${{ env.PREFIX }}{{version}}
            type=semver,pattern=${{ env.PREFIX }}{{major}}.{{minor}}
            type=semver,pattern=${{ env.PREFIX }}{{major}}
            type=raw,value=latest,enable=${{ env.PREREL == 'false' && startsWith(github.ref, 'refs/tags/') }},priority=900

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container images/tags
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
