name: Golang Docker CD

on: [push, pull_request]

jobs:
  deploy-docker-images:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create sanitized github.ref
        run: echo "TAG_USED=$(echo ${GITHUB_REF:10})" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: brenekh/docker-hub-ghcr-test:latest,brenekh/docker-hub-ghcr-test:${{ env.TAG_USED }},ghcr.io/brenekh/docker-hub-ghcr-test:latest,ghcr.io/brenekh/docker-hub-ghcr-test:${{ env.TAG_USED }}
